### ISSUE TITLE
Component not found for specified id.

### ISSUE THREAD

**Issue by rdougan** [Scandit/scandit-react-native-datacapture-parser#3]
I've been trying to get this parser working, however I'm running into the following issue. The camera capture piece is otherwise working. My code:

```
try {
    const context = DataCaptureContext.forLicenseKey('xxx');
    console.log('ensure parser data exists', ParserDataFormat.HIBC);

    const parser = await Parser.forContextAndFormat(context, ParserDataFormat.VIN);
    console.log('parser', parser);

    const data = await parser.parseString('5UXFG2C50DL782277');
    console.log(data); // doesnt get here
} catch(e) {
    console.log(e.message);
    console.log(e.userInfo);
}
```

The error I get is `Component not found for specified id.`

It seems the parser is not getting created. I've stepped through the code in both Xcode and JS - but haven't been able to figure it out.

I've also emailed support@scandit.com

Thanks

**Comment by ScanditSupport** [comment]
@rdougan thanks for reaching out to us directly. We've already followed up on your request and will support you directly with your individual configuration. 

Best regards
Scandit Support
